# Generated by Django 5.0.6 on 2024-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='passcat',
            field=models.CharField(max_length=50, null=True, verbose_name='Password'),
        ),
    ]
