# Generated by Django 5.0.6 on 2024-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_passcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='passcat',
            field=models.CharField(default='sample', max_length=50, verbose_name='Passmot'),
            preserve_default=False,
        ),
    ]
