# Generated by Django 5.0.6 on 2024-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='passcat',
            field=models.CharField(default='patient123', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='passcat',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
