# Generated by Django 5.0.6 on 2024-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50, verbose_name='Patient Name')),
                ('patient_phone', models.CharField(max_length=50, verbose_name='Patient Phone')),
                ('doctor', models.CharField(max_length=50, verbose_name='Doctor')),
                ('service', models.CharField(max_length=50, verbose_name='Service')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Reservation Date')),
            ],
        ),
    ]
