# Generated by Django 5.0.6 on 2024-05-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctor_user_alter_patient_user'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='patient_phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AddField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.doctor', verbose_name='Doctor'),
        ),
    ]
