# Generated by Django 5.0.6 on 2024-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctor_user_alter_patient_user'),
        ('app', '0002_remove_reservation_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Room Number')),
                ('doctor', models.ManyToManyField(to='account.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
