# Generated by Django 5.0.6 on 2024-05-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doctorroom_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorroom',
            name='doctor',
        ),
    ]
